#!/bin/sh

#
# Lint JavaScript, reject failures.
#

# Create a list of changed JS files
files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
if [ "$files" = "" ]; then
    exit 0
fi

pass=true

for file in ${files}; do
    # Ignore Gulp files
    if [ "${file}" = gulp/* ]; then
        continue
    fi

    # Ignore E2E test files
    if [ "${file}" = test/e2e/* ]; then
        continue
    fi

    # Ignore Cordova-provided files
    if [ "${file}" = platforms/* ]; then
        continue
    fi

    result=$(jshint ${file})
    if [ $? -ne 0 ]; then
        echo "JSHint Failed: ${file}"
        echo "${result}"
        pass=false
    fi
done

if ! $pass; then
    echo
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo
    echo "COMMIT FAILED!"
    echo "Your commit contains files that should pass JSHint but do not."
    echo "Please fix the JSHint errors and try again."
    echo
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo
    exit 1
fi
